# Generated by Django 6.0.2 on 2026-03-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
